#!/usr/bin/bash
# Omabar smoke tests. Safe to run anywhere: everything happens in a throwaway
# home folder and a scratch copy of the helper; nothing on the system changes.
#   tests/smoke.sh
set -uo pipefail
ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
O=$ROOT/bin/omabar
SB=$(mktemp -d)
trap 'rm -rf "$SB"' EXIT
pass=0 fail=0
ok() { printf 'ok    %s\n' "$1"; pass=$((pass + 1)); }
no() { printf 'FAIL  %s\n' "$1"; fail=$((fail + 1)); }
t() { if eval "$2"; then ok "$1"; else no "$1"; fi; }

export HOME=$SB
# Never let a test reach the real root helper (and through it, the real Touch Bar).
export OMABAR_HELPER=$SB/no-helper
mkdir -p "$SB/.local/state/omarchy/current/theme" "$SB/.config/hypr" "$SB/.config/omarchy/omabar"
printf -- '-- your binds\n' > "$SB/.config/hypr/bindings.lua"
themes=$(ls -d /usr/share/omarchy/themes/* 2>/dev/null)
first_theme=$(echo "$themes" | head -1)
[[ -n $first_theme ]] && cp "$first_theme/colors.toml" "$SB/.local/state/omarchy/current/theme/"

# Layouts
for id in $("$O" list | python3 -c 'import json,sys; print(" ".join(l["id"] for l in json.load(sys.stdin)["layouts"]))'); do
  t "layout $id renders" "'$O' render $id > '$SB/out.toml' 2>/dev/null && head -1 '$SB/out.toml' | grep -qx '# Generated by omabar'"
done
t "list reports no layout errors" "[[ \$('$O' list | python3 -c 'import json,sys; print(sum(1 for l in json.load(sys.stdin)[\"layouts\"] if l[\"error\"]))') == 0 ]]"

# Colours: default mode is fixed; theme mode stays readable on black for every theme
t "default colours are Omabar's own" "'$O' list | grep -q '\"accent\": \"#82FB9C\"'"
echo '{"colors": "theme"}' > "$SB/.config/omarchy/omabar/rules.json"
for d in $themes; do
  [[ -f $d/colors.toml ]] || continue
  cp "$d/colors.toml" "$SB/.local/state/omarchy/current/theme/colors.toml"
  t "theme $(basename "$d"): every colour readable on black" "'$O' list | python3 -c '
import json, sys
def lum(h):
    c=[int(h[i:i+2],16)/255 for i in (1,3,5)]
    c=[v/12.92 if v<=0.03928 else ((v+0.055)/1.055)**2.4 for v in c]
    return 0.2126*c[0]+0.7152*c[1]+0.0722*c[2]
p=json.load(sys.stdin)[\"palette\"]
sys.exit(0 if all((lum(v)+0.05)/0.05 >= 4.5 for v in p.values()) else 1)'"
done
echo '{}' > "$SB/.config/omarchy/omabar/rules.json"

# Bind block: written once, idempotent, keeps the user's lines
python3 - "$O" <<'EOF' && ok "bind block written once and kept idempotent" || no "bind block written once and kept idempotent"
import importlib.machinery, importlib.util, os, sys
spec = importlib.util.spec_from_loader("om", importlib.machinery.SourceFileLoader("om", sys.argv[1]))
m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
m.sync_binds(); a = open(m.BINDINGS).read(); t = os.stat(m.BINDINGS).st_mtime_ns
m.sync_binds()
assert a.startswith("-- your binds") and a.count(m.BIND_BEGIN) == 1 and os.stat(m.BINDINGS).st_mtime_ns == t
EOF

# Editor commands: key assignment, rules validation, try without a helper
out=$(echo '{"name":"T","buttons":[{"icon":"terminal","tint":"accent","command":"omarchy-launch-terminal"},{"text":"x","command":"echo omabar-test"}]}' | "$O" save t-one 2>&1)
t "save reuses the key of a known command" "echo '$out' | grep -q '\"hyprKey\": \"code:191\"'"
t "save gives a new command a spare key" "echo '$out' | python3 -c 'import json,sys; b=json.load(sys.stdin)[\"layout\"][\"buttons\"][1]; sys.exit(0 if b[\"hyprKey\"] and b[\"key\"] else 1)'"
t "save rejects bad ids" "! echo '{}' | '$O' save 'Bad Id' 2>/dev/null"
t "save rejects path-like icons" "! echo '{\"buttons\":[{\"icon\":\"../x\",\"key\":\"F1\"}]}' | '$O' save t-bad 2>/dev/null"
t "rules reject broken patterns" "! echo '{\"rules\":[{\"app\":\"(\",\"layout\":\"dev\"}]}' | '$O' save-rules 2>/dev/null"
t "rules reject unknown layouts" "! echo '{\"rules\":[{\"app\":\"x\",\"layout\":\"nope\"}]}' | '$O' save-rules 2>/dev/null"
t "try fails safely without a helper" "! echo '{\"buttons\":[{\"text\":\"F1\",\"key\":\"F1\"}]}' | '$O' try 2>/dev/null"
t "built-in layouts can't be deleted" "! '$O' delete dev 2>/dev/null"
t "your layouts can be deleted" "'$O' delete t-one"

# Helper: scratch copy writing to $SB/etc, no root check, no systemctl
H=$SB/helper
sed -e "s|^ETC = \"/etc/tiny-dfr\"|ETC = \"$SB/etc\"|" -e 's|    if os.geteuid() != 0:|    if False:|' \
    -e 's|\["/usr/bin/systemctl", "restart", "tiny-dfr.service"\]|["/usr/bin/true"]|' "$ROOT/system/omabar-helper" > "$H"
chmod +x "$H"; mkdir -p "$SB/etc"; touch "$SB/etc/stock.svg"
pack() { python3 -c '
import sys
out = b""
for spec in sys.argv[1:]:
    n, b = spec.split("=", 1); b = b.encode(); out += n.encode() + b"\n" + str(len(b)).encode() + b"\n" + b
sys.stdout.buffer.write(out)' "$@"; }
t "helper installs real icons" "(cd '$SB/.cache/omabar/icons' && python3 -c '
import os,sys
o=b\"\"
for f in sorted(os.listdir(\".\")):
    b=open(f,\"rb\").read(); o+=f[:-4].encode()+b\"\\n\"+str(len(b)).encode()+b\"\\n\"+b
sys.stdout.buffer.write(o)') | '$H' icons"
t "helper keeps tiny-dfr's own icons" "[[ -f '$SB/etc/stock.svg' ]]"
t "helper rejects path tricks" "! pack '../x=<svg/>' | '$H' icons 2>/dev/null"
t "helper rejects scripts" "! pack 'omabar_x=<svg><script/></svg>' | '$H' icons 2>/dev/null"
t "helper rejects external references" "! pack 'omabar_x=<svg><image href=\"file:///etc/shadow\"/></svg>' | '$H' icons 2>/dev/null"
t "helper rejects foreign configs" "! printf 'X = 1\n' | '$H' config 2>/dev/null"
printf '# Generated by omabar\nA = 1\n' | "$H" config >/dev/null 2>&1
ino=$(stat -c %i "$SB/etc/config.toml")
printf '# Generated by omabar\nA = 2\n' | "$H" config --live >/dev/null 2>&1
t "helper --live rewrites in place" "[[ \$(stat -c %i '$SB/etc/config.toml') == $ino ]] && grep -q 'A = 2' '$SB/etc/config.toml'"

printf '\n%d passed, %d failed\n' "$pass" "$fail"
exit $(( fail > 0 ))
