#!/usr/bin/bash
# Omabar system setup. Run once, as root:
#   sudo ~/.config/omarchy/plugins/io.github.jonathanintheclouds.omabar/system/install.sh
# or press "Set up" in the Omabar panel (it runs this through pkexec).
#
# It is safe to run again; each step checks before it changes anything.
#   1. installs tiny-dfr (from the arch-mact2 repo) if it's missing, and enables it
#   2. sets aside a tiny-dfr config Omabar didn't write
#   3. installs the root helper and a polkit rule so switching needs no password
#   4. installs the resume fix (tiny-dfr dies on suspend on Intel T2 Macs)
#   5. removes the system files of the jonathan.touchbar-layouts prototype
#   6. switches the Touch Bar from Apple's keyboard mode to a display, if it can
#
# Undo with system/uninstall.sh.
set -euo pipefail

say() { printf '%s\n' "$*"; }
die() { printf 'omabar install: %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "run with sudo (or from the panel's Set up button)."
user=${SUDO_USER:-}
if [[ -z $user && -n ${PKEXEC_UID:-} ]]; then
  user=$(id -nu "$PKEXEC_UID")
fi
[[ -n $user && $user != root ]] || die "run with sudo (or pkexec) from your own account."
[[ $user =~ ^[a-z_][a-z0-9_-]*$ ]] || die "unexpected user name: $user"

here=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
model=$(cat /sys/class/dmi/id/product_name 2>/dev/null || true)
if [[ ! $model =~ ^MacBookPro1[56], ]]; then
  say "Warning: this is a '${model:-unknown}', not an Intel T2 MacBook Pro with a Touch Bar."
  say "Omabar is built and tested for MacBookPro15,x and 16,x. Continuing anyway."
fi

# 1. tiny-dfr
if ! command -v tiny-dfr >/dev/null; then
  if pacman -Si tiny-dfr >/dev/null 2>&1; then
    say "Installing tiny-dfr…"
    pacman -S --needed --noconfirm tiny-dfr
  else
    die "tiny-dfr isn't installed and no configured repo has it. Add the arch-mact2 repo (t2linux), then run this again."
  fi
fi
systemctl enable tiny-dfr.service >/dev/null 2>&1 || true

# 2. a config Omabar didn't write would hide the layouts (and the stock one
#    shows plain F-keys); keep it beside the new one.
if [[ -f /etc/tiny-dfr/config.toml ]] && ! head -1 /etc/tiny-dfr/config.toml | grep -qx '# Generated by omabar'; then
  mv -f /etc/tiny-dfr/config.toml "/etc/tiny-dfr/config.toml.before-omabar"
  say "Moved the existing tiny-dfr config to /etc/tiny-dfr/config.toml.before-omabar"
fi

# 3. helper + polkit. The helper is a root-owned copy: Omabar's own files in
#    your home folder are never run as root after this.
install -D -o root -g root -m 755 "$here/omabar-helper" /usr/local/libexec/omabar-helper
cat > /etc/polkit-1/rules.d/50-omabar.rules <<EOF
// Let $user run Omabar's helper without a password, from an active local
// session only. The helper only installs tiny-dfr configs and icons that
// Omabar generated. Installed by Omabar (system/install.sh).
polkit.addRule(function (action, subject) {
  if (action.id == "org.freedesktop.policykit.exec" &&
      action.lookup("program") == "/usr/local/libexec/omabar-helper" &&
      subject.user == "$user" && subject.local && subject.active) {
    return polkit.Result.YES;
  }
});
EOF
chmod 644 /etc/polkit-1/rules.d/50-omabar.rules

# 4. resume fix
install -D -o root -g root -m 644 "$here/99-omabar-tiny-dfr.rules" /etc/udev/rules.d/99-omabar-tiny-dfr.rules
install -D -o root -g root -m 644 "$here/omabar-resume.service" /etc/systemd/system/omabar-resume.service

# 5. the prototype's system files (only ones it marked as its own)
legacy=0
for f in /usr/local/libexec/tiny-dfr-set-config /etc/polkit-1/rules.d/50-tiny-dfr-set-config.rules \
         /etc/udev/rules.d/99-touchbar-tiny-dfr-resume.rules /etc/systemd/system/tiny-dfr-resume.service; do
  if [[ -f $f ]] && grep -q 'jonathan.touchbar-layouts\|tiny-dfr-set-config\|Restart the Touch Bar daemon after resume' "$f"; then
    [[ $f == *.service ]] && systemctl disable "$(basename "$f")" >/dev/null 2>&1 || true
    rm -f "$f"
    legacy=1
  fi
done
if (( legacy )); then
  rm -f /etc/tiny-dfr/omarchy_*.svg
  say "Removed the jonathan.touchbar-layouts prototype's system files and icons."
fi

udevadm control --reload
systemctl daemon-reload
systemctl enable omabar-resume.service >/dev/null 2>&1

# 6. Apple's keyboard mode (USB configuration 1) -> display (configuration 2).
#    tiny-dfr's udev rule does this when the device is added; do it now too.
display_bound() {
  local c
  for c in /sys/class/drm/card[0-9]*; do
    [[ $(basename "$(readlink -f "$c/device/driver" 2>/dev/null)") == appletbdrm ]] && return 0
  done
  return 1
}
if ! display_bound; then
  for d in /sys/bus/usb/devices/*; do
    if [[ $(cat "$d/idVendor" 2>/dev/null) == 05ac && $(cat "$d/idProduct" 2>/dev/null) == 8302 ]]; then
      echo 0 > "$d/bConfigurationValue" 2>/dev/null || true
      echo 2 > "$d/bConfigurationValue" 2>/dev/null || true
    fi
  done
  udevadm settle -t 5 || true
fi
if display_bound; then
  systemctl reset-failed tiny-dfr.service 2>/dev/null || true
  systemctl restart tiny-dfr.service
  say "Done. Pick a layout in the Omabar panel to put it on the Touch Bar."
else
  say "Done, but the Touch Bar is still in Apple's keyboard mode. Reboot once, then pick a layout in the Omabar panel."
fi
