#!/usr/bin/bash
# Remove Omabar's system files. Run as root:
#   sudo ~/.config/omarchy/plugins/io.github.jonathanintheclouds.omabar/system/uninstall.sh
# tiny-dfr itself stays installed; the Touch Bar falls back to tiny-dfr's own
# config (or the one Omabar set aside). Your layouts in ~/.config/omarchy/omabar
# are kept. Remove the plugin with: omarchy plugin remove io.github.jonathanintheclouds.omabar
set -euo pipefail
[[ $EUID -eq 0 ]] || { echo "Run with sudo." >&2; exit 1; }

systemctl disable omabar-resume.service >/dev/null 2>&1 || true
rm -f /usr/local/libexec/omabar-helper /etc/polkit-1/rules.d/50-omabar.rules \
      /etc/udev/rules.d/99-omabar-tiny-dfr.rules /etc/systemd/system/omabar-resume.service \
      /etc/tiny-dfr/omabar_*.svg
if [[ -f /etc/tiny-dfr/config.toml ]] && head -1 /etc/tiny-dfr/config.toml | grep -qx '# Generated by omabar'; then
  if [[ -f /etc/tiny-dfr/config.toml.before-omabar ]]; then
    mv -f /etc/tiny-dfr/config.toml.before-omabar /etc/tiny-dfr/config.toml
  else
    rm -f /etc/tiny-dfr/config.toml
  fi
fi
udevadm control --reload
systemctl daemon-reload
systemctl restart tiny-dfr.service 2>/dev/null || true
echo "Omabar's system files are removed. Remove its bind block from ~/.config/hypr/bindings.lua"
echo "(between '-- omabar begin' and '-- omabar end') if you uninstall the plugin too."
